#!/usr/bin/env zsh

# Exit on error. Append "|| true" if you expect an error.
set -o errexit
# Do not allow use of undefined vars. Use ${VAR:-} to use an undefined VAR
set -o nounset
set -o errreturn
set -o pipefail
#set -o xtrace

# the current directory is where all the dotfiles are
DOTFILES=${0%/*}

# the directory where NVM will be installed
NVM_DIR="$HOME/.nvm"

# Here we load utility functions
fpath=($DOTFILES/funcs $DOTFILES/funcs/dmodules $fpath)
autoload -Uz messages; messages
autoload -Uz gitconfig symlinks modload

gitconfig
symlinks $DOTFILES

# define modules that need to be run
dmodules=(
    utils-setup
    antibody-setup
    zprezto
    gnome-terminal
    rust-setup
    node-setup
    nvim-setup
    docker-setup
    mega-setup
    pipenv-setup
    poetry-setup
    tox-setup
    gcloud-setup
    git-lfs-setup
)

PACKAGES=(
    apt-file
    apt-transport-https
    bison
    ca-certificates
    clang-format
    clangd
    cmake
    curl
    dconf-cli
    docker.io
    docker-compose
    firefox-geckodriver
    flex
    gimp
    gnome-tweaks
    gnupg
    iftop
    imagemagick
    jpegoptim
    libglvnd-dev
    libpq-dev
    linux-tools-generic
    mesa-common-dev
    nethogs
    optipng
    postgresql-client
    python3-pip
    python3-venv
    pngquant
    software-properties-common
    sqlite3
    steam
    steam-devices
    tree
    unzip
    xclip
    xvfb
    tmux
)

SNAP_PACKAGES=(
    bitwarden
    bw
    discord
    drawio
    helm
    slack
    spotify
    telegram-desktop
    vlc
    youtube-dl
)

modload $dmodules

echo    ""
success "  All installed!"

info "Things to do:"
info "  1 - Set the font as the monospace font in gnome-tweaks"
info "  2 - Clone your vault"
info "  3 - Setup gcloud accounts"
info "  4 - Login to Megasync account in desktop app"
info "  5 - Install latest release of gopass: https://github.com/gopasspw/gopass/releases/latest"
info "  6 - Install qt"
info "  7 - Install Firefox addons: Multi-Account Container, Facebook Container"
info "  8 - Install Inkscape and Krita app image, appimaged and AppImageUpdate"
